// Stores the color sequence generated by the game.
let gameSeq = [];

// Stores the colors pressed by the player.
let userSeq = [];

// Available button colors in the Simon game.
let btns = ["red", "green", "yellow", "blue"];

// Tracks the current round number.
let level = 0;

// Tells whether the game has started.
let started = false;

// Keeps the highest score reached in the current session.
let maxScore = 0;

// Reference to the heading that shows the current level and game-over message.
let h2 = document.querySelector("h2");
let start = document.querySelector(".start")

// Start the game when the user presses any key.
start.addEventListener("click", function() {
    // Prevent restarting the game during an active round.
    if(started == false){
        // console.log("Game Started!");
        started = true;

        // Begin the first level.
        levelUp();
    }
})

// Add a short flash animation to the computer-generated button.
function btnFlash(btn){
    btn.classList.add("flash");

    setTimeout(function() {
        btn.classList.remove("flash");
    }, 250);
}

// Add a separate flash animation for the player's clicked button.
function userFlash(btn){
    btn.classList.add("userFlash");

    setTimeout(function() {
        btn.classList.remove("userFlash");
    }, 130);
}

// Move the game to the next level by adding one random color to the sequence.
function levelUp(){
    // Clear the player's answer at the start of every new level.
    userSeq = [];

    // Increase the round number.
    level++;

    // Show the new level in the heading.
    h2.innerText = "Level " + level;

    // Pick a random button color from the available list.
    let rndIdx = Math.floor(Math.random() * 4);
    let rndCol = btns[rndIdx];
    let rndBtn = document.querySelector(`.${rndCol}`);

    // console.log(rndIdx);
    // console.log(rndCol);
    // console.log(rndBtn);

    // Store the new color in the sequence for the computer to display.
    gameSeq.push(rndCol);
    // console.log(gameSeq);

    // Flash the selected button to show the player the sequence.
    btnFlash(rndBtn);
}

// Compare the player's click with the game sequence at the current position.
function checkAns(idx) {
    // console.log("Curr level is", level);

    // If the current click matches the expected color, continue.
    if(gameSeq[idx] === userSeq[idx]){
        // When the whole sequence has been matched, move to the next level.
        if(userSeq.length == gameSeq.length){
            setTimeout(levelUp, 1000);
        }

        // console.log("Same Value");
    }else{
        // Update the highest score using the current level.
        maxScore = Math.max(maxScore, (level-1)*10);

        // Display game-over text with the score and best score.
        h2.innerHTML = `<p class="over">Game Over!!</p> <p class="score">Your score is <b>${(level-1)*10}<b/> <br/> Highest score is ${maxScore} </p><h2 class="start">Click on this text to start.</h2>`;

        // Briefly darken the background to signal a loss.
        let body = document.querySelector("body");

        body.classList.add("black");
        setTimeout(function(){
            body.classList.remove("black");
        }, 100);

        // Reset the game state for a fresh start.
        reset();
    }
}

// Handle the player's click on a color button.
function userBtnPress() {
    // console.log(this);
    let btn = this;

    // Show the player's click animation.
    userFlash(btn);

    // Read the button's id so we can compare it with the game sequence.
    userCol = btn.getAttribute("id");
    // console.log(userCol);

    // Save the player's chosen color in the answer array.
    userSeq.push(userCol);
    // console.log(userSeq);

    // Check whether the player's input is correct.
    checkAns(userSeq.length-1);
}

// Attach the click handler to every colored button.
let allBtns = document.querySelectorAll(".btn")
for(btn of allBtns){
    btn.addEventListener("click", userBtnPress);
}

// Reset all game variables so the next round can start cleanly.
function reset() {
    started = false;
    gameSeq = [];
    userSeq = [];
    level = 0;
}